### ISSUE TITLE
List all features

### ISSUE THREAD

**Issue by rainfore** [vusion/css-sprite-loader#3]
### 最简单的

``` css
{
    background: url(xxx.png?sprite);
}
```
或
``` css
{
    background-image: url(xxx.png?sprite);
}
```
转换为
``` css
{
    background: url(sprite.ag9290jh8.png) -200px -500px no-repeat;
}
```

### 有position
``` css
{
    background: url(xxx.png?sprite) 20px 40px;
}
```
或
``` css
{
    background-image: url(xxx.png?sprite);
    background-position: 20px 40px;
}
```
转换为
``` css
{
    background: url(sprite.ag9290jh8.png) -180px -460px no-repeat;
}
```

### 有background-size
``` css
{
    background: url(xxx.png?sprite);
    background-size: 200px 100px;
}
```
或
``` css
{
    background-image: url(xxx.png?sprite);
    background-size: 200px 100px;
}
```
转换为
``` css
{
    background: url(sprite.ag9290jh8.png) -200px -500px no-repeat;
    background-size: 200px 100px;
}
```

### 有repeat
``` css
{
    background: url(xxx.png?sprite) repeat-x;
}
```
或
``` css
{
    background-image: url(xxx.png?sprite) repeat-x;
    background-repeat: repeat-x;
}
```
转换为
``` css
{
    background: url(sprite-x.ag9290jh8.png) 0 -500px repeat-x;
}
```

### 用image-set
``` css
{
    background: image-set(url(xxx.png?sprite) 1x, url(xxx@2x.png?sprite) 2x);
    background-size: 200px 100px;
}
```
转换为
``` css
{
    background: image-set(url(sprite.ag9290jh8.png) 1x, url(sprite@2x.ag9290jh8.png) 2x);
}
```
